
install.packages('readxl')
install.packages('tseries')
#install.packages("githubinstall")
#install_github("nickpoison/astsa")
library("readxl")
pil_veneto <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_veneto.xlsx", sheet = "Sheet1")
pil_lazio <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_lazio.xlsx")
pil_toscana <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_toscana.xlsx")
pil_liguria <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_liguria.xlsx")
pil_lombardia <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_lombardia.xlsx")  
pil_campania <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_campania.xlsx")
pil_piemonte <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_piemonte.xlsx")
pil_emilia <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_emilia.xlsx")
pil_sicilia <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_sicilia.xlsx")
pil_puglia <- read_excel("C:\\Users\\edobo\\OneDrive\\Desktop\\Thesis\\Medieval Guilds\\Data\\EDITED_db\\pil\\pil_attempt_puglia.xlsx")

#regression for veneto
model_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_veneto)
detrended_veneto <- resid(model_1)

pil_veneto$year_factor <- as.factor(pil_veneto$year)
agg_change_veneto <- lm(agg_change ~ time(agg_change), data=pil_veneto) 
detrended_agg_change <- resid(agg_change_veneto)
lagged1_veneto = c(NA, head(detrended_veneto, -1))
lagged2_veneto = c(rep(NA, 2), head(pil_veneto$region_new_guilds, -2))
lagged3_veneto = c(rep(NA, 3), head(pil_veneto$region_new_guilds, -3))
lagged4_veneto = c(rep(NA, 4), head(pil_veneto$region_new_guilds, -4))
lagged5_veneto = c(rep(NA, 5), head(pil_veneto$region_new_guilds, -5))
regressor_veneto = (lagged3_veneto + lagged4_veneto)
pil_veneto_ts <- ts(pil_veneto$group, start=c(1400), frequency=40)
model <- lm(agg_change ~ lagged3_veneto, data=pil_veneto)
summary(model)
model <- lm(agg_change ~ lagged4_veneto, data=pil_veneto)
summary(model)
model <- lm(agg_change ~ regressor_veneto, data=pil_veneto)
summary(model)
length(pil_veneto$agg_change)
ccf_result <- ccf(pil_veneto$agg_change, pil_veneto$region_new_guilds, lag.max = 20, plot = TRUE)


#regression for lazio
model_lazio_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_lazio)
detrended_lazio <- resid(model_lazio_1)
agg_change_lazio <- lm(agg_change ~ time(agg_change), data=pil_lazio)
detrended_agg_change_lazio <- resid(agg_change_lazio)
lagged4_lazio <- c(rep(NA, 4), head(pil_lazio$region_new_guilds, -4))
lagged3_lazio <- c(rep(NA, 3), head(pil_lazio$region_new_guilds, -3))
lagged2_lazio <- c(rep(NA, 2), head(pil_lazio$region_new_guilds, -2))
lagged1_vector <- c(NA, head(pil_lazio$region_new_guilds, -1))
lagged_pil <- c(NA, head(detrended_agg_change_lazio, -1))
regressor_lazio = (lagged3_lazio + lagged4_lazio)
pil_lazio_ts <- ts(pil_lazio$group, start=c(1400), frequency=40)
model_lazio <- lm(agg_change ~ lagged3_lazio , data=pil_lazio)
summary (model_lazio)
model_lazio <- lm(agg_change ~ lagged4_lazio , data=pil_lazio)
summary(model_lazio)
model_lazio <- lm(agg_change ~ regressor_lazio , data=pil_lazio)
summary(model_lazio)
length(pil_lazio$agg_change)
ccf_result <- ccf(pil_lazio$agg_change, pil_lazio$region_new_guilds, lag.max = 20, plot = TRUE)

#regression for toscana
model_toscana_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_toscana)
detrended_toscana <- resid(model_toscana_1)
lagged4_toscana <- c(rep(NA, 4), head(pil_toscana$region_new_guilds, -4))
lagged3_toscana <- c(rep(NA, 3), head(detrended_toscana, -3))
lagged2_toscana <- c(rep(NA, 2), head(detrended_toscana, -2))
lagged1_toscana <- c(NA, head(detrended_toscana, -1))

agg_change_toscana <- lm(agg_change ~ time(agg_change), data=pil_toscana)   
detrended_agg_change_toscana <- resid(agg_change_toscana)
regressor_toscana <- (lagged3_toscana + lagged4_toscana)
model_toscana <- lm(agg_change ~ lagged3_toscana, data=pil_toscana) 
summary(model_toscana)
model_toscana <- lm(agg_change ~ lagged4_toscana, data=pil_toscana)
summary(model_toscana)

model_toscana <- lm(agg_change ~ regressor_toscana, data=pil_toscana)
summary(model_toscana)
length(pil_toscana$agg_change)
ccf_result <- ccf(pil_toscana$agg_change, pil_toscana$region_new_guilds, lag.max = 20, plot = TRUE)

#regression for liguria 
model_liguria_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_liguria)
detrended_liguria <- resid(model_liguria_1)

lagged4_liguria <- c(rep(NA, 4), head(detrended_liguria, -4))
lagged3_liguria <- c(rep(NA, 3), head(detrended_liguria, -3))
lagged2_liguria <- c(rep(NA, 2), head(detrended_liguria, -2))
lagged1_liguria <- c(NA, head(detrended_liguria, -1))
agg_change_liguria <- lm(agg_change ~ time(agg_change), data=pil_liguria)
detrended_agg_change_liguria <- resid(agg_change_liguria)
regressor_liguria <- (lagged3_liguria + lagged2_liguria)
model_liguria <- lm(agg_change ~ lagged3_liguria, data=pil_liguria)
summary(model_liguria)
model_liguria <- lm(agg_change ~ lagged4_liguria, data=pil_liguria)
summary(model_liguria)

model_liguria <- lm(agg_change ~ regressor_liguria, data=pil_liguria)
summary(model_liguria)
length(pil_liguria$agg_change)
ccf_result <- ccf(pil_liguria$agg_change, pil_liguria$region_new_guilds, lag.max = 20, plot = TRUE)
correlation <- cor(pil_liguria$agg_change, pil_liguria$region_new_guilds, use="complete.obs")

#regression for lombardia
model_lombardia_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_lombardia)
detrended_lombardia <- resid(model_lombardia_1)
lagged10_lombardia <- c(rep(NA, 10), head(pil_lombardia$region_new_guilds, -10))
lagged5_lombardia <- c(rep(NA, 5), head(pil_lombardia$region_new_guilds, -5))
lagged4_lombardia <- c(rep(NA, 4), head(pil_lombardia$region_new_guilds, -4))
lagged3_lombardia <- c(rep(NA, 3), head(pil_lombardia$region_new_guilds, -3))
lagged2_lombardia <- c(rep(NA, 2), head(pil_lombardia$region_new_guilds, -2))
lagged1_lombardia <- c(NA, head(pil_lombardia$region_new_guilds, -1))
rolling_avg_GDP_lombardia <- lm(rolling_avg_GDP ~ time(rolling_avg_GDP), data=pil_lombardia)
detrended_rolling_avg_GDP_lombardia <- resid(rolling_avg_GDP_lombardia)
regressor_lombardia <- (lagged3_lombardia + lagged4_lombardia)
model_lombardia <- glm(agg_change ~ lagged3_lombardia, data=pil_lombardia)
summary(model_lombardia)
model_lombardia <- glm(agg_change ~ lagged4_lombardia, data=pil_lombardia)
summary(model_lombardia)
model_lombardia <- glm(agg_change ~ regressor_lombardia, data=pil_lombardia)
length(pil_lombardia$agg_change)
summary(model_lombardia)

#regression for campania
model_campania_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_campania)
detrended_campania <- resid(model_campania_1)
lagged5_campania <- c(rep(NA, 5), head(pil_campania$region_new_guilds, -5))
lagged4_campania <- c(rep(NA, 4), head(pil_campania$region_new_guilds, -4))
lagged3_campania <- c(rep(NA, 3), head(pil_campania$region_new_guilds, -3))
lagged2_campania <- c(rep(NA, 2), head(pil_campania$region_new_guilds, -2))
lagged1_campania <- c(NA, head(pil_campania$region_new_guilds, -1))
agg_change_campania <- lm(agg_change ~ time(agg_change), data=pil_campania)
detrended_agg_change_campania <- resid(agg_change_campania)
lagged3_4_campania = lagged3_campania + lagged4_campania
rolling_avg_GDP_campania <- lm(rolling_avg_GDP ~ time(rolling_avg_GDP), data=pil_campania)
detrended_rolling_avg_GDP_campania <- resid(rolling_avg_GDP_campania)
pil_campania_ts <- ts(pil_campania$group, start=c(1400), frequency=20)
model_campania <- lm(agg_change ~ lagged3_campania, data=pil_campania)
summary(model_campania)
model_campania <- lm(agg_change ~ lagged4_campania, data=pil_campania)
summary(model_campania)
model_campania <- lm(agg_change ~ lagged3_4_campania , data=pil_campania)
summary(model_campania)
length(pil_campania$agg_change)
ccf_result <- ccf(pil_campania$agg_change, pil_campania$region_new_guilds, lag.max = 20, plot = TRUE)
correlation <- cor(pil_campania$agg_change, pil_campania$region_new_guilds, use="complete.obs")

#regression for piemonte
model_piemonte_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_piemonte)
detrended_piemonte <- resid(model_piemonte_1)
lagged5_piemonte <- c(rep(NA, 5), head(detrended_piemonte, -5))
lagged4_piemonte <- c(rep(NA, 4), head(detrended_piemonte, -4)) 
lagged3_piemonte <- c(rep(NA, 3), head(detrended_piemonte, -3))
lagged2_piemonte <- c(rep(NA, 2), head(pil_piemonte$region_new_guilds, -2))
lagged1_piemonte <- c(NA, head(pil_piemonte$region_new_guilds, -1))
regressor_piemonte <- (lagged3_piemonte + lagged2_piemonte)
agg_change_piemonte <- lm(agg_change ~ time(agg_change), data=pil_piemonte)
detrended_agg_change_piemonte <- resid(agg_change_piemonte)
rolling_avg_GDP_piemonte <- lm(rolling_avg_GDP ~ time(rolling_avg_GDP), data=pil_piemonte)
detrended_rolling_avg_GDP_piemonte <- resid(rolling_avg_GDP_piemonte)
lagged3_4_piemonte = lagged3_piemonte + lagged4_piemonte
pil_piemonte_ts <- ts(pil_piemonte$group, start=c(1400), frequency=20)
model_piemonte <- lm(agg_change ~ lagged3_piemonte, data=pil_piemonte)
summary(model_piemonte)
model_piemonte <- lm(agg_change ~ lagged4_piemonte, data=pil_piemonte)  
summary(model_piemonte)
model_piemonte <- lm(agg_change ~ lagged3_4_piemonte, data=pil_piemonte)
summary(model_piemonte)
length(pil_piemonte$agg_change)
ccf_result <- ccf(pil_piemonte$agg_change, pil_piemonte$region_new_guilds, lag.max = 20, plot = TRUE)

#regression for emilia
model_emilia_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_emilia)
detrended_emilia <- resid(model_emilia_1)
lagged5_emilia <- c(rep(NA, 5), head(detrended_emilia, -5))
lagged4_emilia <- c(rep(NA, 4), head(detrended_emilia, -4))
lagged3_emilia <- c(rep(NA, 3), head(detrended_emilia, -3))
lagged2_emilia <- c(rep(NA, 2), head(pil_emilia$region_new_guilds, -2))
lagged1_emilia <- c(NA, head(pil_emilia$region_new_guilds, -1))
agg_change_emilia <- lm(agg_change ~ time(agg_change), data=pil_emilia)
detrended_agg_change_emilia <- resid(agg_change_emilia)
rolling_avg_GDP_emilia <- lm(rolling_avg_GDP ~ time(rolling_avg_GDP), data=pil_emilia)
detrended_rolling_avg_GDP_emilia <- resid(rolling_avg_GDP_emilia)
lagged3_4_emilia = lagged3_emilia + lagged4_emilia
model_emilia <- glm(agg_change ~ lagged3_emilia, data=pil_emilia)
summary(model_emilia)
model_emilia <- glm(agg_change ~ lagged4_emilia, data=pil_emilia)
summary(model_emilia)
model_emilia <- glm(agg_change ~ lagged3_4_emilia, data=pil_emilia)
summary(model_emilia)
length(pil_emilia$agg_change)
ccf_result <- ccf(pil_emilia$agg_change, pil_emilia$region_new_guilds, lag.max = 20, plot = TRUE)

#regression for sicilia
model_sicilia_1 <- lm(region_new_guilds ~ time(region_new_guilds), data=pil_sicilia)
detrended_sicilia <- resid(model_sicilia_1)
lagged5_sicilia <- c(rep(NA, 5), head(pil_sicilia$region_new_guilds, -5))
lagged4_sicilia <- c(rep(NA, 4), head(pil_sicilia$region_new_guilds, -4))
lagged3_sicilia <- c(rep(NA, 3), head(detrended_sicilia, -3))
lagged2_sicilia <- c(rep(NA, 2), head(pil_sicilia$region_new_guilds, -2))
lagged1_sicilia <- c(NA, head(pil_sicilia$region_new_guilds, -1))
agg_change_sicilia <- lm(agg_change ~ time(agg_change), data=pil_sicilia)
detrended_agg_change_sicilia <- resid(agg_change_sicilia)
rolling_avg_GDP_sicilia <- lm(rolling_avg_GDP ~ time(rolling_avg_GDP), data=pil_sicilia)
detrended_rolling_avg_GDP_sicilia <- resid(rolling_avg_GDP_sicilia)
pil_sicilia_ts <- ts(pil_sicilia$group, start=c(1400), frequency=20)
lagged3_4_sicilia = lagged3_sicilia + lagged4_sicilia
model_sicilia <- lm(agg_change ~ lagged3_sicilia, data=pil_sicilia)
summary(model_sicilia)
model_sicilia <- lm(agg_change ~ lagged4_sicilia, data=pil_sicilia) 
summary(model_sicilia)
model_sicilia <- lm(agg_change ~ lagged3_4_sicilia, data=pil_sicilia)
summary(model_sicilia)
length(pil_sicilia$agg_change)

